version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/data"
      - ./conf/rabbit.basic.config.json:/etc/rabbitmq/rabbitmq.config
volumes:
  rabbitmq_data:
